[build]
  publish = "."
  command = "echo 'No build command needed for static site'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# URL redirects for school-specific links
[[redirects]]
  from = "/school/:school"
  to = "/index.html?school=:school"
  status = 200

# Default redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
